name: Sankarshan Mridha's blog
title: Sankarshan Mridha
url: https://msank00.github.io
baseurl: ""
twitter_username: imridhasankar
github_username:  msank00
linkedin_username: sankarshanmridha
description: On machine learning, deep learning, nlp, computer vision, statistics and other areas of data science
author: Sankarshan Mridha
# email: sanakarshan7@gmail.com
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
theme: minima
highlighter: rouge

kramdown:
  input: GFM
  # https://github.com/jekyll/jekyll/pull/4090
  syntax_highlighter: rouge

  # Rouge Highlighter in Kramdown › http://kramdown.gettalong.org/syntax_highlighter/rouge.html
  # span, block element options fall back to global
  syntax_highlighter_opts:
    # Rouge Options › https://github.com/jneen/rouge#full-options
    css_class: 'highlight'
    #line_numbers: true # bad idea, spans don't need linenos and would inherit this option
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

plugins:
  - "disqus-for-jekyll"
  - jekyll-feed
  - jemoji
  - rouge

header_pages:
  #- resume.md
  - publications.md
  - blog/index.html
  - index.md
